main: xyz.reknown.fastercrystals.FasterCrystals
name: $name
version: $version
author: Jyguy
folia-supported: true
api-version: "$apiVersion"
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
